// <auto-generated />
using System;
using BasketCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasketCore.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20200913141540_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasketCore.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Court")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameType")
                        .HasColumnType("int");

                    b.Property<string>("OpponentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Court = "Staples Center",
                            Date = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameType = 0,
                            OpponentName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 2,
                            Court = "Wells Fargo Center",
                            Date = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameType = 1,
                            OpponentName = "Philadelphia 76ers"
                        },
                        new
                        {
                            Id = 3,
                            Court = "New Orleans Arena",
                            Date = new DateTime(2020, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameType = 1,
                            OpponentName = "New Orleans Pelicans"
                        },
                        new
                        {
                            Id = 4,
                            Court = "United Center",
                            Date = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameType = 2,
                            OpponentName = "Chicago Bulls"
                        },
                        new
                        {
                            Id = 5,
                            Court = "AT&T Center",
                            Date = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameType = 1,
                            OpponentName = "San Antonio Spurs"
                        });
                });

            modelBuilder.Entity("BasketCore.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("StatsId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1988, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Patrick",
                            Height = 185.0,
                            LastName = "Beverley",
                            Number = 21,
                            Position = 0,
                            StatsId = 0,
                            Weight = 81.599999999999994
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            Height = 203.0,
                            LastName = "George",
                            Number = 13,
                            Position = 2,
                            StatsId = 0,
                            Weight = 99.799999999999997
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1991, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kawhi",
                            Height = 201.0,
                            LastName = "Leonard",
                            Number = 2,
                            Position = 2,
                            StatsId = 0,
                            Weight = 102.09999999999999
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1986, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lou",
                            Height = 185.0,
                            LastName = "Williams",
                            Number = 23,
                            Position = 1,
                            StatsId = 0,
                            Weight = 79.400000000000006
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1997, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivica",
                            Height = 213.0,
                            LastName = "Zubac",
                            Number = 40,
                            Position = 4,
                            StatsId = 0,
                            Weight = 108.90000000000001
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1994, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Montrezl",
                            Height = 201.0,
                            LastName = "Harrell",
                            Number = 5,
                            Position = 3,
                            StatsId = 0,
                            Weight = 108.90000000000001
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1990, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Reggie",
                            Height = 190.0,
                            LastName = "Jackson",
                            Number = 1,
                            Position = 1,
                            StatsId = 0,
                            Weight = 94.299999999999997
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1997, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Landry",
                            Height = 193.0,
                            LastName = "Shamet",
                            Number = 20,
                            Position = 1,
                            StatsId = 0,
                            Weight = 86.200000000000003
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1989, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marcus",
                            Height = 203.0,
                            LastName = "Morris Sr.",
                            Number = 31,
                            Position = 3,
                            StatsId = 0,
                            Weight = 98.900000000000006
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1990, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "JaMychal",
                            Height = 203.0,
                            LastName = "Green",
                            Number = 4,
                            Position = 2,
                            StatsId = 0,
                            Weight = 103.0
                        });
                });

            modelBuilder.Entity("BasketCore.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Blocks")
                        .HasColumnType("int");

                    b.Property<int>("Fauls")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rebounds")
                        .HasColumnType("int");

                    b.Property<int>("Steals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assists = 3,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 1,
                            PlayerId = 1,
                            Points = 5,
                            Rebounds = 2,
                            Steals = 0
                        },
                        new
                        {
                            Id = 2,
                            Assists = 3,
                            Blocks = 1,
                            Fauls = 3,
                            GameId = 1,
                            PlayerId = 2,
                            Points = 25,
                            Rebounds = 6,
                            Steals = 1
                        },
                        new
                        {
                            Id = 3,
                            Assists = 6,
                            Blocks = 1,
                            Fauls = 3,
                            GameId = 1,
                            PlayerId = 3,
                            Points = 30,
                            Rebounds = 8,
                            Steals = 3
                        },
                        new
                        {
                            Id = 4,
                            Assists = 7,
                            Blocks = 0,
                            Fauls = 4,
                            GameId = 1,
                            PlayerId = 4,
                            Points = 12,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 5,
                            Assists = 2,
                            Blocks = 4,
                            Fauls = 5,
                            GameId = 1,
                            PlayerId = 5,
                            Points = 5,
                            Rebounds = 11,
                            Steals = 1
                        },
                        new
                        {
                            Id = 6,
                            Assists = 4,
                            Blocks = 3,
                            Fauls = 4,
                            GameId = 1,
                            PlayerId = 6,
                            Points = 11,
                            Rebounds = 10,
                            Steals = 1
                        },
                        new
                        {
                            Id = 7,
                            Assists = 3,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 1,
                            PlayerId = 7,
                            Points = 5,
                            Rebounds = 2,
                            Steals = 0
                        },
                        new
                        {
                            Id = 8,
                            Assists = 2,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 1,
                            PlayerId = 8,
                            Points = 14,
                            Rebounds = 2,
                            Steals = 0
                        },
                        new
                        {
                            Id = 9,
                            Assists = 2,
                            Blocks = 1,
                            Fauls = 1,
                            GameId = 1,
                            PlayerId = 9,
                            Points = 15,
                            Rebounds = 2,
                            Steals = 1
                        },
                        new
                        {
                            Id = 10,
                            Assists = 1,
                            Blocks = 1,
                            Fauls = 3,
                            GameId = 1,
                            PlayerId = 10,
                            Points = 5,
                            Rebounds = 3,
                            Steals = 0
                        },
                        new
                        {
                            Id = 11,
                            Assists = 11,
                            Blocks = 0,
                            Fauls = 4,
                            GameId = 2,
                            PlayerId = 1,
                            Points = 9,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 12,
                            Assists = 5,
                            Blocks = 1,
                            Fauls = 4,
                            GameId = 2,
                            PlayerId = 2,
                            Points = 22,
                            Rebounds = 3,
                            Steals = 0
                        },
                        new
                        {
                            Id = 13,
                            Assists = 4,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 2,
                            PlayerId = 3,
                            Points = 40,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 14,
                            Assists = 12,
                            Blocks = 0,
                            Fauls = 4,
                            GameId = 2,
                            PlayerId = 4,
                            Points = 11,
                            Rebounds = 4,
                            Steals = 0
                        },
                        new
                        {
                            Id = 15,
                            Assists = 7,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 2,
                            PlayerId = 5,
                            Points = 3,
                            Rebounds = 5,
                            Steals = 1
                        },
                        new
                        {
                            Id = 16,
                            Assists = 2,
                            Blocks = 1,
                            Fauls = 5,
                            GameId = 2,
                            PlayerId = 6,
                            Points = 15,
                            Rebounds = 11,
                            Steals = 1
                        },
                        new
                        {
                            Id = 17,
                            Assists = 9,
                            Blocks = 1,
                            Fauls = 2,
                            GameId = 2,
                            PlayerId = 7,
                            Points = 9,
                            Rebounds = 5,
                            Steals = 0
                        },
                        new
                        {
                            Id = 18,
                            Assists = 4,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 2,
                            PlayerId = 8,
                            Points = 20,
                            Rebounds = 2,
                            Steals = 1
                        },
                        new
                        {
                            Id = 19,
                            Assists = 3,
                            Blocks = 3,
                            Fauls = 2,
                            GameId = 2,
                            PlayerId = 9,
                            Points = 10,
                            Rebounds = 6,
                            Steals = 0
                        },
                        new
                        {
                            Id = 20,
                            Assists = 0,
                            Blocks = 2,
                            Fauls = 4,
                            GameId = 2,
                            PlayerId = 10,
                            Points = 10,
                            Rebounds = 5,
                            Steals = 1
                        },
                        new
                        {
                            Id = 21,
                            Assists = 11,
                            Blocks = 0,
                            Fauls = 3,
                            GameId = 3,
                            PlayerId = 1,
                            Points = 7,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 22,
                            Assists = 8,
                            Blocks = 1,
                            Fauls = 5,
                            GameId = 3,
                            PlayerId = 2,
                            Points = 29,
                            Rebounds = 6,
                            Steals = 0
                        },
                        new
                        {
                            Id = 23,
                            Assists = 5,
                            Blocks = 1,
                            Fauls = 5,
                            GameId = 3,
                            PlayerId = 3,
                            Points = 37,
                            Rebounds = 5,
                            Steals = 3
                        },
                        new
                        {
                            Id = 24,
                            Assists = 4,
                            Blocks = 1,
                            Fauls = 2,
                            GameId = 3,
                            PlayerId = 4,
                            Points = 18,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 25,
                            Assists = 1,
                            Blocks = 0,
                            Fauls = 6,
                            GameId = 3,
                            PlayerId = 5,
                            Points = 10,
                            Rebounds = 9,
                            Steals = 1
                        },
                        new
                        {
                            Id = 26,
                            Assists = 2,
                            Blocks = 2,
                            Fauls = 2,
                            GameId = 3,
                            PlayerId = 6,
                            Points = 6,
                            Rebounds = 11,
                            Steals = 1
                        },
                        new
                        {
                            Id = 27,
                            Assists = 5,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 3,
                            PlayerId = 7,
                            Points = 4,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 28,
                            Assists = 5,
                            Blocks = 2,
                            Fauls = 1,
                            GameId = 3,
                            PlayerId = 8,
                            Points = 6,
                            Rebounds = 0,
                            Steals = 2
                        },
                        new
                        {
                            Id = 29,
                            Assists = 3,
                            Blocks = 1,
                            Fauls = 5,
                            GameId = 3,
                            PlayerId = 9,
                            Points = 16,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 30,
                            Assists = 1,
                            Blocks = 2,
                            Fauls = 2,
                            GameId = 3,
                            PlayerId = 10,
                            Points = 11,
                            Rebounds = 4,
                            Steals = 0
                        },
                        new
                        {
                            Id = 41,
                            Assists = 6,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 4,
                            PlayerId = 1,
                            Points = 9,
                            Rebounds = 2,
                            Steals = 2
                        },
                        new
                        {
                            Id = 42,
                            Assists = 5,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 4,
                            PlayerId = 2,
                            Points = 23,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 43,
                            Assists = 4,
                            Blocks = 1,
                            Fauls = 3,
                            GameId = 4,
                            PlayerId = 3,
                            Points = 29,
                            Rebounds = 9,
                            Steals = 2
                        },
                        new
                        {
                            Id = 44,
                            Assists = 9,
                            Blocks = 1,
                            Fauls = 1,
                            GameId = 4,
                            PlayerId = 4,
                            Points = 10,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 45,
                            Assists = 2,
                            Blocks = 3,
                            Fauls = 4,
                            GameId = 4,
                            PlayerId = 5,
                            Points = 11,
                            Rebounds = 9,
                            Steals = 0
                        },
                        new
                        {
                            Id = 46,
                            Assists = 3,
                            Blocks = 2,
                            Fauls = 3,
                            GameId = 4,
                            PlayerId = 6,
                            Points = 15,
                            Rebounds = 11,
                            Steals = 0
                        },
                        new
                        {
                            Id = 47,
                            Assists = 8,
                            Blocks = 0,
                            Fauls = 1,
                            GameId = 4,
                            PlayerId = 7,
                            Points = 4,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 48,
                            Assists = 1,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 4,
                            PlayerId = 8,
                            Points = 13,
                            Rebounds = 5,
                            Steals = 1
                        },
                        new
                        {
                            Id = 49,
                            Assists = 3,
                            Blocks = 1,
                            Fauls = 1,
                            GameId = 4,
                            PlayerId = 9,
                            Points = 13,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 50,
                            Assists = 2,
                            Blocks = 1,
                            Fauls = 2,
                            GameId = 4,
                            PlayerId = 10,
                            Points = 8,
                            Rebounds = 3,
                            Steals = 0
                        },
                        new
                        {
                            Id = 51,
                            Assists = 7,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 1,
                            Points = 5,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 52,
                            Assists = 8,
                            Blocks = 1,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 2,
                            Points = 24,
                            Rebounds = 5,
                            Steals = 1
                        },
                        new
                        {
                            Id = 53,
                            Assists = 5,
                            Blocks = 2,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 3,
                            Points = 32,
                            Rebounds = 6,
                            Steals = 1
                        },
                        new
                        {
                            Id = 54,
                            Assists = 3,
                            Blocks = 2,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 4,
                            Points = 15,
                            Rebounds = 5,
                            Steals = 2
                        },
                        new
                        {
                            Id = 55,
                            Assists = 4,
                            Blocks = 2,
                            Fauls = 4,
                            GameId = 5,
                            PlayerId = 5,
                            Points = 9,
                            Rebounds = 13,
                            Steals = 2
                        },
                        new
                        {
                            Id = 56,
                            Assists = 3,
                            Blocks = 2,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 6,
                            Points = 15,
                            Rebounds = 8,
                            Steals = 4
                        },
                        new
                        {
                            Id = 57,
                            Assists = 2,
                            Blocks = 2,
                            Fauls = 3,
                            GameId = 5,
                            PlayerId = 7,
                            Points = 6,
                            Rebounds = 4,
                            Steals = 1
                        },
                        new
                        {
                            Id = 58,
                            Assists = 1,
                            Blocks = 1,
                            Fauls = 1,
                            GameId = 5,
                            PlayerId = 8,
                            Points = 12,
                            Rebounds = 3,
                            Steals = 1
                        },
                        new
                        {
                            Id = 59,
                            Assists = 4,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 9,
                            Points = 10,
                            Rebounds = 4,
                            Steals = 0
                        },
                        new
                        {
                            Id = 60,
                            Assists = 4,
                            Blocks = 0,
                            Fauls = 2,
                            GameId = 5,
                            PlayerId = 10,
                            Points = 7,
                            Rebounds = 2,
                            Steals = 1
                        });
                });

            modelBuilder.Entity("BasketCore.Models.Stats", b =>
                {
                    b.HasOne("BasketCore.Models.Game", "Game")
                        .WithMany("Stats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BasketCore.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
